### PR TITLE
Create kloak.spec

### PR DESCRIPTION
**Pull request by siliconwaffle**
Spec file for rpm, specifically for Fedora.

This pull request changes...

## Mandatory Checklist

- [ x ] Legal agreements accepted. By contributing to this organisation, you acknowledge you have read, understood, and agree to be bound by these these agreements:

[Terms of Service](https://www.whonix.org/wiki/Terms_of_Service), [Privacy Policy](https://www.whonix.org/wiki/Privacy_Policy), [Cookie Policy](https://www.whonix.org/wiki/Cookie_Policy), [E-Sign Consent](https://www.whonix.org/wiki/E-Sign_Consent), [DMCA](https://www.whonix.org/wiki/DMCA), [Imprint](https://www.whonix.org/wiki/Imprint)

## Optional Checklist
The following items are optional but might be requested in certain cases.

- [ x ] I have tested it locally
- [ x ] I have reviewed and updated any documentation if relevant
- [ ] I am providing new code and test(s) for it

Fixes #

### CODE REVIEW

**Comment by ArrayBolt3** [comment]
This works great for me on Fedora 40, however the kloak service is not enabled by default after installation since there is no systemd preset file. Not really a bug, the user can always enable it themselves, but since the Debian package for kloak does automatically enable it after installation, it might be worth considering.

**Comment by siliconwaffle** [comment]
> This works great for me on Fedora 40, however the kloak service is not enabled by default after installation since there is no systemd preset file. Not really a bug, the user can always enable it themselves, but since the Debian package for kloak does automatically enable it after installation, it might be worth considering.

Actually good point, I didn't think about it. Right now I have a review request open to get it into the Fedora repos, so I'll have to look after the packaging guidelines again to make sure I'm able to enable it by default, but iirc I should be able to. I've never made a systemd preset file before, so if you know how to and can make a PR it would be appreciated.

**Comment by ArrayBolt3** [comment]
I can try to take a look when I have some free time.

**Comment by ArrayBolt3** [comment]
@adrelanos https://docs.fedoraproject.org/en-US/packaging-guidelines/DefaultServices/

**Comment by siliconwaffle** [comment]
@ArrayBolt3 so for the preset, as far as I can tell in Fedora's case *all* default services are handled by a single preset file provided in fedora-release-common package. I'm debating whether I should include a preset file in this repository for the spec but for the Fedora rpm exclude the preset so that it can be handled by fedora-release-common. What do you think?

**Pull request merged**
